prometheus-node-exporter:
  hostRootFsMount:
    enabled: false

# adds additional scrape configs to prometheus.yml
# must be a string so you have to add a | after extraScrapeConfigs:
# example adds prometheus-blackbox-exporter scrape config
extraScrapeConfigs: |
  - job_name: 'keycloak-exporter'
    metrics_path: /auth/realms/master/metrics
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - host.docker.internal:8080

