extensions:
  health_check:
  zpages:
    endpoint: :55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true
        cors:
          allowed_origins:
            - http://localhost:4200 # Angular/React SPA
          max_age: 7200

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    # verbosity: detailed
  file/traces:
    path: /log/otel/traces.log
  file/metrics:
    path: /log/otel/metrics.log
  file/logs:
    path: /log/otel/logs.log
  otlp/tempo:
    endpoint: "${TEMPO_ENDPOINT}"
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: "${LOKI_ENDPOINT}"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    
service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - debug 
        - file/traces
        - otlp/tempo
    metrics:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - debug
        - file/metrics
        - prometheus
    logs:
      receivers:
        - otlp
      processors: [batch]
      exporters:
        - debug
        - file/logs
        - otlphttp/loki
  extensions:
    - health_check
    - zpages
